CREATE TABLE IF NOT EXISTS state (
    ID SMALLINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,

    PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS address (
    ID         BIGINT(11) UNSIGNED AUTO_INCREMENT,
    state      SMALLINT UNSIGNED NOT NULL,
    city       VARCHAR(100) NOT NULL,
    district   VARCHAR(100) NOT NULL,
    street     VARCHAR(100) NOT NULL,
    number     INT(11) NOT NULL,
    cep        INT(11) NOT NULL,
    complement TEXT,

    PRIMARY KEY(ID),

    FOREIGN KEY (state)
    REFERENCES
        state(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS employee (
    ID      BIGINT(11) UNSIGNED AUTO_INCREMENT,
    name    VARCHAR(50) DEFAULT NULL,
    surname VARCHAR(100) DEFAULT NULL,
    age     INT(11) DEFAULT NULL,
    childs  SMALLINT(11) UNSIGNED DEFAULT 0,

    PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS contract (
    ID           BIGINT(11) UNSIGNED AUTO_INCREMENT,
    registration VARCHAR(100) NOT NULL,
    admission    DATE NOT NULL,
    wage         FLOAT DEFAULT NULL,
    office       VARCHAR(30) NOT NULL,

    PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;