CREATE TABLE IF NOT EXISTS region (
    ID   SMALLINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,

    PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS state (
    UF   CHAR(2),
    name VARCHAR(255) NOT NULL UNIQUE,
    region SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY(UF),

    FOREIGN KEY (region)
    REFERENCES
        region(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS address (
    ID         BIGINT UNSIGNED AUTO_INCREMENT,
    state      CHAR(2) NOT NULL,
    city       VARCHAR(100) NOT NULL,
    district   VARCHAR(100) NOT NULL,
    street     VARCHAR(100) NOT NULL,
    number     INT NOT NULL,
    cep        INT NOT NULL,
    complement TEXT,

    PRIMARY KEY(ID),

    FOREIGN KEY (state)
    REFERENCES
        state(UF)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS contract (
    ID           BIGINT UNSIGNED AUTO_INCREMENT,
    registration VARCHAR(100) NOT NULL,
    admission    DATE NOT NULL,
    wage         DECIMAL(11, 2) NOT NULL,
    office       VARCHAR(30) NOT NULL,

    PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS employee (
    CPF      BIGINT UNSIGNED,
    name     VARCHAR(50) DEFAULT NULL,
    surname  VARCHAR(100) DEFAULT NULL,
    age      INT DEFAULT NULL,
    sons     SMALLINT UNSIGNED DEFAULT 0,
    address  BIGINT UNSIGNED NOT NULL,
    contract BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY(CPF),

    FOREIGN KEY (address)
    REFERENCES
        address(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

    FOREIGN KEY (contract)
    REFERENCES
        contract(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;